# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d8a6a2493f14040203e4f3775b49db9e8310c5a1e0525c722f64d3104212475d4d10b148c9ca71e35a943a04e9a149f43b7f65c2209d879e33dde77aab7356c

test:
  secret_key_base: 9445623a867f6ad707d113b7f436d1c5a7fd34a964c8ebbf8ea631c4c31a2dc1e01e7996abff2ae179a522075fcb7851f2b97f7a4cea9f77fb57eb907dfb3e17

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
